name: Push-to-tienda-online-saas-EC2-Linux

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push to tienda-online-saas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files now
        uses: actions/checkout@v2

      - name: Deploy to Server1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}